version: "3"
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    volumes:
      - "rabbitmq_data:/data"
  users_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: users_service_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: password
  users_api:
    depends_on:
      - users_db
    build: microservices/user_microservice
    restart: unless-stopped
    environment:
      DB_DRIVER: postgresql+psycopg2
      DB_USER: my_user
      DB_PASSWORD: password
      DB_HOST: users_db
      DB_PORT: 5432
      DB_DATABASE: users_service_db
      SECRET_JWT_KEY: my_secre1_key
    command:
      - "entrypoint_api.sh"
  books_db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: books_service_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: password
  books_api:
    build: microservices/book_microservice
    restart: unless-stopped
    depends_on:
      - books_db
    environment:
      DB_DRIVER: postgresql+psycopg2
      DB_USER: my_user
      DB_PASSWORD: password
      DB_HOST: books_db
      DB_PORT: 5432
      DB_DATABASE: books_service_db
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    command:
      - "entrypoint_api.sh"
  books_api_cli:
    build: microservices/book_microservice
    restart: on-failure
    depends_on:
      - rabbitmq
    environment:
      DB_DRIVER: postgresql+psycopg2
      DB_USER: my_user
      DB_PASSWORD: password
      DB_HOST: books_db
      DB_PORT: 5432
      DB_DATABASE: books_service_db
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    command:
      - "entrypoint_cli.sh"
  books_api_consumer:
    build: microservices/book_microservice
    restart: unless-stopped
    environment:
      DB_DRIVER: postgresql+psycopg2
      DB_USER: my_user
      DB_PASSWORD: password
      DB_HOST: books_db
      DB_PORT: 5432
      DB_DATABASE: books_service_db
      RABBITMQ_USER: user
      RABBITMQ_PASSWORD: password
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
    command:
      - "entrypoint_consumer.sh"
  nginx:
    image: nginx:1.19.0-alpine
    depends_on:
      - users_api
    #      - books_api
    ports:
      - "1234:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
volumes:
  rabbitmq_data: