@startuml

header Финальный проект по итогу обучения
title Схема БД

hide circle
skinparam linetype ortho


entity Users {
    * **id**  :  int
    --
    * **email**  :  text
    __
    * **password**  : text
    __
    * **login**  :  text
    __
    **name**  :  text
    __
    **age**  :  int
}


@enduml

